routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


/*Route::group(['prefix'=>'admin'],function(){

	Route::resource('about','ControllerAboutMe');
 
});*/
Route::resource('about', 'ControllerAboutMe');

Route::get('about/destroy/{id}', ['as' => 'about/destroy','uses'=>'ControllerAboutMe@destroy']);
//Route for search method
Route::post('about/search',['as'=>'about/search','uses'=>'ControllerAboutMe@search']);
//Route for update method
Route::put('about/update',['as' => 'about/update','uses'=>'ControllerAboutMe@update']);
//Route for store method
Route::post('about/store',['as' => 'about/store','uses'=>'ControllerAboutMe@store']);
//Route for searchInstructors methodcity

Route::resource('city','ControllerCities');

Route::get('city/destroy/{id}', ['as' => 'city/destroy','uses'=>'ControllerCities@destroy']);
//Route for search method
Route::post('city/search',['as'=>'city/search','uses'=>'ControllerCities@search']);
//Route for update method
Route::put('city/update',['as' => 'city/update','uses'=>'ControllerCities@update']);
//Route for store method
Route::post('city/store',['as' => 'city/store','uses'=>'ControllerCities@store']);
//Route for searchInstructors method

Route::resource('jobs','ControllerJobs');

Route::get('jobs/destroy/{id}', ['as' => 'jobs/destroy','uses'=>'ControllerJobs@destroy']);
//Route for search method
Route::post('jobs/search',['as'=>'jobs/search','uses'=>'ControllerJobs@search']);
//Route for update method
Route::put('jobs/update',['as' => 'jobs/update','uses'=>'ControllerJobs@update']);
//Route for store method
Route::post('jobs/store',['as' => 'jobs/store','uses'=>'ControllerJobs@store']);
//Route for searchInstructors method 

Route::resource('services','ControllerServicies');

Route::get('services/destroy/{id}', ['as' => 'services/destroy','uses'=>'ControllerServicies@destroy']);
//Route for search method
Route::post('services/search',['as'=>'services/search','uses'=>'ControllerServicies@search']);
//Route for update method
Route::put('services/update',['as' => 'services/update','uses'=>'ControllerServicies@update']);
//Route for store method
Route::post('services/store',['as' => 'services/store','uses'=>'ControllerServicies@store']);
//Route for searchInstructors method
 
Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/', 'WelcomeController@index');

resources/views/about/create.blade.php
@extends ('admin.template.main')
	@section('title','Home')  
	
		@section('content')

         	{!! Form::open(['route' => 'about.store', 'method' => 'POST']) !!}

         	   <h1>Acerca de mi</h1>

              <div class="form-group">
              	
              	<label class="control-label">A contianuación  podra registrar información personal:</label>
              </div>

              <div class="form-group">
              
              		{!! Form::label('description','Descripción') !!}
              		{!! Form::text('description',null,['class'=> 'form-control','placeholder'=>'Escriba el contenido que desea mostrar acerca de usted','required']) !!}
              
              </div>

              
               <div class="form-group">
              
              		{!! Form::label('years','Año de publicación') !!}
              		{!! Form::text('years',null,['class'=> 'form-control','placeholder'=>'Ejemplo:2018','required']) !!}
              
              </div>
          
               <div class="form-group">
              
              		{!! Form::submit('Registrar',['class'=>'btn btn-primary']) !!}
              		
              
              </div>

         	{!! Form::close() !!}

		@endsection
	

resources/views/about/list.blade.php
@extends('admin.template.main')
@section('content')
	<div>
		<a class="btn btn-success" href="{{ route('about.create') }}">Crear</a>
		<hr>
		<section>
			<table class="table table-hover">
				<thead class="thead-inverse">
					<tr>
						<th>Descripción</th>						
						<th>Años</th>  
					</tr>
				</thead>
				<tbody>
					@foreach($about as $value)
						<tr>
							<td>{{ $value->description }}</td>	
							<td>{{ $value->years }}</td>				
							<td>
								<a class="btn btn-primary btn-xs" href="{{ route('about.edit',['id' => $value->id] )}}" >
									Editar
								</a> 
							</td> 
						</tr>
					@endforeach
				</tbody>
			</table>
	</div>
@endsection

resources/views/about/update.blade.php
@extends ('admin.template.main')
	@section('title','Home')  
	
		@section('content')

         	{!! Form::open(['route' => 'about/update', 'method' => 'PUT']) !!}

         	   <h1>Acerca de mi</h1>

              <div class="form-group">
              	
              	<label class="control-label">A contianuación  podra registrar información personal:</label>
              </div>

              <div class="form-group">
                  {!! Form::hidden('id', $about->id) !!}
              
              		{!! Form::label('description','Descripción') !!}
              		{!! Form::text('description',$about->description,['class'=> 'form-control','placeholder'=>'Escriba el contenido que desea mostrar acerca de usted','required']) !!}
              
              </div>

              
               <div class="form-group">
              
              		{!! Form::label('years','Año de publicación') !!}
              		{!! Form::text('years',$about->years,['class'=> 'form-control','placeholder'=>'Ejemplo:2018','required']) !!}
              
              </div>
          
               <div class="form-group">
              
              		{!! Form::submit('Actualizar',['class'=>'btn btn-primary']) !!}
              		
              
              </div>

         	{!! Form::close() !!}

		@endsection
	